version: '3.8'
services:
    app:
        build: .
        image: py-server
        container_name: py-flask-server
        volumes:
            - app:/app
        ports:
            - 8080:8080
            
volumes:
    app:
        driver: local
        driver_opts: 
            type: none
            o: bind
            device: C:\docker\py-sever\app\
